// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookOwnershipController from "./book_ownership_controller"
application.register("book-ownership", BookOwnershipController)

import CategoryEditController from "./category_edit_controller"
application.register("category-edit", CategoryEditController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
